### ISSUE TITLE
Error in variable name (iceServers)

### ISSUE THREAD

**Issue by rahul7827** [ant-media/videojs-webrtc-plugin#9]
Hello Tahir

Thanks for the latest update, I got minor issues in developer console during implementation.

**Error in console**

`VIDEOJS: SyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)
    at WebRTCHandler.initiateWebRTCAdaptor (videojs-webrtc-plugin.js:837:26)
    at new WebRTCHandler (videojs-webrtc-plugin.js:808:12)
    at Object.handleSource (videojs-webrtc-plugin.js:1070:21)
    at Html5._Tech.setSource (video.js:12200:32)
    at Player.<anonymous> (video.js:26378:31)
    at Player.ready (video.js:4389:12)
    at Player.techCall_ (video.js:26369:12)
    at Player.<anonymous> (video.js:27671:16)
    at Player.ready (video.js:4389:12)`

**Steps to Reproduce**

VERSION : 1.1.0

1. Clone the repo
2. Install dependency
3. Create build

SCRIPT this way

`<script>
const iceServers = '[{"urls": "stun:stun1.l.google.com:19302"}]';
    var player = videojs('videojs-webrtc-player');

    player.src({
      src: 'wss://DOMAIN.com:5443/WebRTCAppEE/streamx.webrtc',
      iceServers: iceServers
    });

    player.on('ant-error', function(event, errors) {
      console.log("Player error", errors);
    });

</script>`

After applying breakpoint here -> (videojs-webrtc-plugin.js:837:26). I found spelling mistake in iceServer

`this.source.pcConfig = {
        iceServers: JSON.parse(source.iceservers)
      };`

After changing the spelling of **iceservers** in index.html file error disappeared from console.

One more thing that can be improved is : 

You have used videojs id : (videojs-webrtc-player) in index.html file. While in **README.md** id (my-video) has been used everywhere.

Also when I run index.html it throws error : 

`Uncaught TypeError: examplePlayer.antmediaWebrtc is not a function
    at HTMLFormElement.<anonymous> (index.html:85:47)`

**Comment by golgetahir** [comment]
Thanks @rahul7827 noted, I will change the index.html completely according to your feedbacks, it is left from the older versions currently. And thanks for noticing the naming issue. Any commit from you is also welcomed on this repo!
